import { Cart } from "../cart/getUserCart";
import { UserAddressInterface } from "./checkoutTypes";

export const dummyUserAddresses: UserAddressInterface[] = [
  {
    id: "addr-001",
    addressLabel: "Rumah",
    userId: "user-001",
    receiverName: "Budi Santoso",
    receiverPhoneNumber: "081234567890",
    addressDisplayName: "Jl. Merpati No. 45, Bandung",
    addressDetails: "Gang samping Indomaret, rumah cat biru pagar hitam",
    lat: "-6.917464",
    lon: "107.619123",
    isDefault: true,
    province: "Jawa Barat",
    city: "Bandung",
    district: "Cicendo",
    districtId: 3201010,
  },
  {
    id: "addr-002",
    addressLabel: "Kantor",
    userId: "user-001",
    receiverName: "Budi Santoso",
    receiverPhoneNumber: "081298765432",
    addressDisplayName: "Gedung Graha IT, Lantai 5, Jakarta",
    addressDetails: "Dekat Mall Kota Kasablanka",
    lat: "-6.21462",
    lon: "106.84513",
    isDefault: false,
    province: "DKI Jakarta",
    city: "Jakarta Selatan",
    district: "Tebet",
    districtId: 3175050,
  },
  {
    id: "addr-003",
    addressLabel: "Kos",
    userId: "user-001",
    receiverName: "Budi Santoso",
    receiverPhoneNumber: "089876543210",
    addressDisplayName: "Jl. Anggrek No. 12, Sleman",
    addressDetails: "Sebelah warung makan Bu Tini",
    lat: "-7.775241",
    lon: "110.374046",
    isDefault: false,
    province: "DI Yogyakarta",
    city: "Sleman",
    district: "Depok",
    districtId: 3404040,
  },
];

export const dummyCart: Cart = {
  id: "cart-001",
  userId: "user-001",
  items: [
    {
      id: "item-001",
      productId: "prod-001",
      storeId: "store-001",
      quantity: 1,
      product: {
        id: "prod-001",
        name: "Laptop ASUS ROG Zephyrus",
        price: 20000000,
        picture1: "/images/products/laptop-rog.jpg",
      },
      activePrice: 20000000,
      discountAmount: 2000000,
      appliedDiscount: {
        id: "disc-001",
        name: "Diskon 10% Opening Store",
        type: "AUTOMATIC",
        valueType: "PERCENTAGE",
        value: 10,
        maxDiscountAmount: null,
      },
      bogo: null,
      availability: {
        status: "AVAILABLE",
        currentStock: 5,
      },
    },
    {
      id: "item-002",
      productId: "prod-002",
      storeId: "store-001",
      quantity: 2,
      product: {
        id: "prod-002",
        name: "Mouse Logitech G Pro X Superlight",
        price: 2200000,
        picture1: "/images/products/mouse-logitech.jpg",
      },
      activePrice: 2200000,
      discountAmount: 0,
      appliedDiscount: null,
      bogo: {
        buyQuantity: 2,
        getQuantity: 1,
        applyToSameProduct: true,
        maxBogoSets: 1,
      },
      availability: {
        status: "AVAILABLE",
        currentStock: 10,
      },
    },
    {
      id: "item-003",
      productId: "prod-003",
      storeId: "store-002",
      quantity: 1,
      product: {
        id: "prod-003",
        name: "Mechanical Keyboard Keychron K2",
        price: 1300000,
        picture1: "/images/products/keyboard-keychron.jpg",
      },
      activePrice: 1300000,
      discountAmount: 130000,
      appliedDiscount: {
        id: "disc-002",
        name: "Diskon 10% Weekend",
        type: "AUTOMATIC",
        valueType: "PERCENTAGE",
        value: 10,
        maxDiscountAmount: null,
      },
      bogo: null,
      availability: {
        status: "AVAILABLE",
        currentStock: 15,
      },
    },
  ],
};